### PR TITLE
✨ feat: get started module

### PR DESCRIPTION
**Pull request by deleteLater**
Implement a get started module to help new users learn how to use FeatBit.

### CODE REVIEW

**Comment by cosmic-flood** [comment]
Chanting:Review PR

**Comment by cosmic-flood** [comment]
Chanting:Review PR

**Comment by cosmic-flood** [comment]
Chanting:Review PR

**Comment by cosmic-flood** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by cosmic-flood** [comment]
image

@deleteLater @cosmos-explorer

**Review by cosmos-explorer — DISMISSED** [review]

**Review by cosmic-flood — APPROVED** [review]

**Pull request merged**
