### PR TITLE
📖 docs: add design contribution guidelines

### PR DESCRIPTION
**Pull request by fivenp**
Hey there. 

I really loved using FeatBit and thought you might be open for not only code but also design contributions. 
Designers would require a little bit of a different context than engineers so I wanted to prepare these docs for you and get the project listed at https://contribute.design to get visibility across designers.

I'm not 100% sure about the flow I'm proposing and the design relevant materials you potentially already have – so feel free to change or propose changes :)

### CODE REVIEW

**Comment by cosmic-flood** [comment]
contribute.design looks like a cool idea. 
 
 I tried to understand how it works from the link you proposed to us https://contribute.design/featbit/featbit. 
 
 🐛But I got this error. Maybe you need to fix it ? 

image

**Comment by fivenp** [comment]
Oh that's embarrassing :) 

It was indeed a bug on our end – thank you so much for reporting it... we just fixed it :)

**Comment by cosmic-flood** [comment]
How to modify the introduction of the project?   @fivenp 

image

**Comment by fivenp** [comment]
This gets currently pulled straight from the projects `About` description on GitHub

**Review by cosmic-flood — APPROVED** [review]

**Pull request merged**
