### PR TITLE
✨ feat: add api to retrieve the latest data for the server and client sdks

### PR DESCRIPTION
**Pull request by deleteLater**
### get latest feature flags & segments for server-side sdk

request with
```shell
curl -H "Authorization: the-env-secret" http://localhost:5100/api/public/sdk/server/latest-all
```
example output
```json
{
   "messageType":"data-sync",
   "data":{
      "eventType":"full",
      "featureFlags":[
         {
            "envId":"1331554d-98c4-41fe-ade4-68e6f5eeb54a",
            "name":"hello world",
            "key":"hello-world",
            "variationType":"boolean",
            "variations":[
               {
                  "id":"bbe8f444-090e-4a3b-99fa-b487bab424aa",
                  "value":"true"
               },
               {
                  "id":"cf8f9626-0d6f-4d05-a98f-8c3a50c85d0f",
                  "value":"false"
               }
            ],
            "targetUsers":[
               
            ],
            "rules":[
               
            ],
            "isEnabled":true,
            "disabledVariationId":"cf8f9626-0d6f-4d05-a98f-8c3a50c85d0f",
            "fallthrough":{
               "dispatchKey":null,
               "includedInExpt":true,
               "variations":[
                  {
                     "id":"bbe8f444-090e-4a3b-99fa-b487bab424aa",
                     "rollout":[
                        0,
                        1
                     ],
                     "exptRollout":1
                  }
               ]
            },
            "exptIncludeAllTargets":true,
            "tags":[
               
            ],
            "isArchived":false,
            "disabledVariation":{
               "id":"cf8f9626-0d6f-4d05-a98f-8c3a50c85d0f",
               "value":"false"
            },
            "creatorId":"b58fa8fd-eca2-460a-ab0f-e7758dbcec6a",
            "updatorId":"b58fa8fd-eca2-460a-ab0f-e7758dbcec6a",
            "createdAt":"2023-03-16T09:11:23.739Z",
            "updatedAt":"2023-03-16T09:11:26.0465535Z",
            "id":"4daca70f-86ae-4468-aee8-afc700977202"
         }
      ],
      "segments":[
         {
            "envId":"1331554d-98c4-41fe-ade4-68e6f5eeb54a",
            "name":"beta users",
            "description":"this is a segment for beta users",
            "included":[
               
            ],
            "excluded":[
               
            ],
            "rules":[
               
            ],
            "isArchived":false,
            "createdAt":"2023-03-16T09:18:21.1317917Z",
            "updatedAt":"2023-03-16T09:18:21.1317248Z",
            "id":"b2b91bbe-5d54-4d8a-882f-afc700995b23"
         }
      ]
   }
}
```

### get latest variations for client-side sdk

request with
```shell
curl -X POST http://localhost:5100/api/public/sdk/client/latest-all \
-H 'Content-Type: application/json' \
-H 'Authorization: the-env-secret' \
-d '{
    "keyId": "bot-id",
    "name": "bot",
    "customizedProperties": [
        {
            "name": "level",
            "value": "high"
        },
        {
            "name": "localtion",
            "value": "us"
        }
    ]
}'
```
example output
```json
[
    {
       "id":"hello-world",
       "variation":"true",
       "variationType":"boolean"
    }
]
```

### CODE REVIEW

**Comment by cosmos-explorer** [comment]
Why so many params when fetching data for client-side sdk
`http://localhost:5100/api/public/Sdk/client/latest-all?keyId=bot-id&name=bot&customizedProperties[0].name=level&customizedProperties[0].value=high&customizedProperties[1].name=location&customizedProperties[1].value=us`

**Comment by deleteLater** [comment]
Because I think it's really a [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) operation, not a [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) operation. It's safe and idempotent.

**Comment by cosmos-explorer** [comment]
> Because I think it's really a [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) operation, not a [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) operation. It's safe and idempotent.

But a GET request makes it really difficult to create this url

**Comment by cosmos-explorer** [comment]
LGTM

**Pull request merged**
